apiVersion: v1
kind: Service
metadata:
  name: task-server-service
spec:
  type: NodePort
  selector:
    app: task-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
